server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/foodcourt_users
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
appDescription: "FoodCourt users microservice"
appVersion: "1.0.0"
